---
title: "house"
author: "Koki Ando"
date: "5/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


[House Price Prediction](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data)

```{r}
library(tidyverse)
test = read.csv("test.csv")
train = read.csv("train.csv")
```

# EDA

```{r}
dim(train)
```

## Summary of train

```{r}
# summary(train)
```

## Sale Price

```{r}
train %>% 
  ggplot(aes(SalePrice)) +
  geom_histogram(bins = 50)
```

```{r}
summary(train$SalePrice)
```

## Missing values

```{r}
apply(train, 2, prop_miss)
```


### Dealing with Missing values

#### Combine datasets

```{r}
test$SalePrice = 0
train$Train = "YES"
test$Train = "NO"
merged_dat = rbind(train, test)
```

#### Check NAs again

```{r}
prop_miss(merged_dat)
```

```{r}
library(naniar)
library(simputation)
sort(apply(merged_dat, 2, n_miss), decreasing = T)
```

```{r}
merged_dat %>% 
  miss_var_summary() %>%
  filter(n_miss >= 1 & n_miss < 5) %>% 
  filter(variable %in% vars)
```

```{r}
vars = c("MSZoning", "Utilities", "BsmtFullBath", "BsmtHalfBath", "Functional", "Exterior1st", "Exterior2nd", 
         "BsmtFinSF1", "BsmtFinSF2", "BsmtUnfSF", "TotalBsmtSF", "Electrical", "KitchenQual", "GarageCars", "GarageArea", "SaleType")
```

```{r}
merged_dat %>% 
  select(vars) %>% 
  str()
```

```{r}
vars_int = c("BsmtFullBath", "BsmtHalfBath", "BsmtFinSF1", "BsmtFinSF2", "BsmtUnfSF", "TotalBsmtSF", "GarageCars", "GarageArea")
vars_factor = c("MSZoning", "Utilities", "Functional", "Exterior1st", "Exterior2nd", "Electrical", "KitchenQual", "SaleType")
merged_dat = impute_mean_at(merged_dat, vars_int)
merged_dat = merged_dat %>% 
  impute_cart(MSZoning ~ .) %>% 
  impute_cart(Utilities ~ .) %>% 
  impute_cart(Functional ~ .) %>% 
  impute_cart(Exterior1st ~ .) %>% 
  impute_cart(Exterior2nd ~ .) %>% 
  impute_cart(Electrical ~ .) %>% 
  impute_cart(KitchenQual ~ .) %>% 
  impute_cart(SaleType ~ .)
```

# Check NAs

```{r}
miss_var_summary(merged_dat)
```



## Top 7 missing values

```{r}
miss_var_summary(merged_dat)
```

```{r}
top_missing_vats = c("PoolQC", "MiscFeature", "Alley", "Fence", "FireplaceQu", "LotFrontage", "GarageYrBlt")
merged_dat %>% 
  select(top_missing_vats, SalePrice) %>% 
  str()
```


## Deeper EDA

### PoolQC

```{r}
merged_dat %>% 
  ggplot(aes(SalePrice, PoolQC)) +
  geom_boxplot()
```

```{r}
merged_dat %>% 
  bind_shadow() %>% 
  ggplot(aes(SalePrice, colour = PoolQC_NA)) +
  geom_density()
```



```{r}
nums <- unlist(lapply(merged_dat, is.numeric))  
res <- cor(merged_dat[, nums])
round(res, 2) %>% tail(1)
```

```{r}
merged_dat %>% 
  bind_shadow() %>% 
  ggplot(aes(TotalBsmtSF, SalePrice, colour = Alley_NA)) +
  geom_point(alpha = .4)
```




```{r}
merged_dat = select(merged_dat, -PoolQC, -MiscFeature, -Alley, -Fence)
merged_dat = select(merged_dat, -Fence)
```


```{r}
prop_miss(merge_dat)
miss_var_summary(select(merged_dat, contains("Garage")))
```


## Garage

```{r}
merged_dat %>% 
  select(contains("Garage"), SalePrice) %>% 
  str()
```


```{r}
merged_dat %>% 
  select(contains("Garage"), SalePrice) %>% 
  # bind_shadow() %>% 
  add_label_missings() %>% 
  ggplot(aes(GarageYrBlt, SalePrice), alpha = .4) +
  geom_point() +
  geom_miss_point()
```


```{r}
merged_dat %>% 
  ggplot(aes(GarageYrBlt, SalePrice)) +
  geom_point() +
  geom_miss_point()
```

### Linear Model imputation

```{r}
merged_dat = impute_lm(merged_dat, GarageYrBlt ~ SalePrice)
```

```{r}
nums <- unlist(lapply(merged_dat, is.numeric))  
res <- cor(merged_dat[, nums])
round(res, 2)[26:27,]
```


```{r}
merged_dat %>% 
  select(contains("Garage"), SalePrice) %>% 
  ggplot(aes(GarageYrBlt, SalePrice)) +
  geom_point() +
  geom_miss_point()
```


### Garage Type/Qual/Cond/Finish

```{r}
merged_dat %>% 
  ggplot(aes(GarageFinish)) +
  geom_bar(stat = "count")
# merged_dat %>% 
#   ggplot(aes(GarageQual, SalePrice, colour = GarageQual)) +
#   geom_boxplot()
# 
# merged_dat %>% 
#   ggplot(aes(SalePrice, colour = GarageQual)) +
#   geom_density()
```

##### Mode Imputation

```{r}
merged_dat[is.na(merged_dat$GarageType),]$GarageType = "Attchd"
merged_dat[is.na(merged_dat$GarageQual),]$GarageQual = "TA"
merged_dat[is.na(merged_dat$GarageCond),]$GarageCond = "TA"
merged_dat[is.na(merged_dat$GarageFinish),]$GarageFinish = "Unf"
```




```{r}
prop_miss(merged_dat)
```


#### Imputation

```{r}
Mode = function(x){
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
```



# Baseline prediction

```{r}
train = merged_dat %>% 
  filter(Train == "YES") %>% 
  select(-Train)
test = merged_dat %>% 
  filter(Train == "NO") %>% 
  select(-Train, -SalePrice)
```



```{r}
library(rpart)
library(randomForest)
model_rpart = rpart(data = train, SalePrice ~ .)
# model_rf = randomForest(SalePrice ~ ., data = train,
#                         ntree = 500, importance = TRUE)


test$SalePrice = predict(model_rf, test)
submission = select(test, Id, SalePrice)
write.csv(submission, "submission.csv", row.names = FALSE)
```

